### PR TITLE
v0.8-dev

### PR DESCRIPTION
**Pull request by BRaimbault**
v0.8 Pre-Release

**Change list:**
- project re-organization
- Indicators / IndicatorGroups / Data Sets views abandonned
- fine tunning
- moved Service description storage (cf doc)
- includes dossiersEditor app
- added Search tab
- added Graph tab
- update doc to v0.8
- maybe something else...

### CODE REVIEW

**Comment by BRaimbault** [comment]
You can check the pre-release here:
https://github.com/MSFOCBA/dhis2Reports/releases

.., and decide whether you'd like to merge or not.

New way to store descriptions is explained here: 
https://github.com/MSFOCBA/dhis2Reports/tree/v0.8-dev/doc

I take the chance to thank you for your work on the app and I hope you'll like the changes!
Happy to recieve comments/ideas! FYI we will be testing this pre-release soon so we can move to release over the next weeks.

Bruno

Wow Great work! I really like the search and the information visualization, kind of a semantic web. Maybe needs a bit of tweaking to be able to be intuitive for users.

Rishi

**Comment by RishiMSF** [comment]
Wow Great work! I really like the search and the information visualization, kind of a semantic web. Maybe needs a bit of tweaking to be able to be intuitive for users. Thanks for sharing!

Rishi

**Comment by RishiMSF** [comment]
Some bugs I used be struggling with seem to be back(or perhaps they never were away). The loading gif keeps continue  loading sometimes, Also the disable print button is sometimes not disabled also a bug that pestered me bit. The bugs are related to event handling, Probably I did it a bit messy, so it was not so intuitive for you guys. Simplest solution is to disable the loading gif and the disable print button functionality until it is fully solved.

Cheers, Rishi

**Comment by BRaimbault** [comment]
Thanks for flagging up these two issues.
I reckon I have not paid too much attention to it as Services are not properly defined yet and requests logically fail in these cases.

I'll follow up on that.

The graph has been produced quickly in order to decide whether it is an informative way to display the services elements or not. Of course not definitive. 

Some ideas that popped out on:

What could be most interesting to visualize:
- shared dataelements
- indicators <-> dataelements relationships

Then some functionalities to add:
- filtering based on element types
- underline elements relationships (currently double click, maybe switch to hover over)

Happy to receive suggestions!
Bruno

**Pull request merged**
